# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gkBETA_cpp <- function(beta, phi, i, k, nbeta, nphi, A, Y, TCOV, delta, nw) {
    .Call('_trajeR_gkBETA_cpp', PACKAGE = 'trajeR', beta, phi, i, k, nbeta, nphi, A, Y, TCOV, delta, nw)
}

difLBETA_cpp <- function(param, ng, nx, nbeta, nphi, n, A, Y, X, TCOV, nw) {
    .Call('_trajeR_difLBETA_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, nphi, n, A, Y, X, TCOV, nw)
}

LikelihoodBETA_cpp <- function(param, ng, nx, nbeta, nphi, n, A, Y, X, TCOV, nw) {
    .Call('_trajeR_LikelihoodBETA_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, nphi, n, A, Y, X, TCOV, nw)
}

gkCNORM_cpp <- function(beta, sigma, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw) {
    .Call('_trajeR_gkCNORM_cpp', PACKAGE = 'trajeR', beta, sigma, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw)
}

difLbetakalpha_cpp <- function(theta, beta, alpha, delta, k, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call('_trajeR_difLbetakalpha_cpp', PACKAGE = 'trajeR', theta, beta, alpha, delta, k, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

difLsigmaalphaunique_cpp <- function(theta, beta, alpha, delta, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call('_trajeR_difLsigmaalphaunique_cpp', PACKAGE = 'trajeR', theta, beta, alpha, delta, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

difLalpha_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, ssigma) {
    .Call('_trajeR_difLalpha_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, ssigma)
}

difLalphaunique_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, ssigma) {
    .Call('_trajeR_difLalphaunique_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, ssigma)
}

Likelihoodalpha_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, ssigma) {
    .Call('_trajeR_Likelihoodalpha_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, ssigma)
}

likelihoodCNORM_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call('_trajeR_likelihoodCNORM_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

likelihoodEM_cpp <- function(n, ng, nbeta, beta, sigma, pi, A, Y, ymin, ymax, TCOV, delta, nw) {
    .Call('_trajeR_likelihoodEM_cpp', PACKAGE = 'trajeR', n, ng, nbeta, beta, sigma, pi, A, Y, ymin, ymax, TCOV, delta, nw)
}

ftauxCNORM_cpp <- function(pi, beta, sigma, ng, nbeta, n, A, Y, ymin, ymax, TCOV, delta, nw, nx, X) {
    .Call('_trajeR_ftauxCNORM_cpp', PACKAGE = 'trajeR', pi, beta, sigma, ng, nbeta, n, A, Y, ymin, ymax, TCOV, delta, nw, nx, X)
}

EM_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EM_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

EMSigmaunique_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EMSigmaunique_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

EMCensored_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EMCensored_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

EMCensoredSigmaunique_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EMCensoredSigmaunique_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

IEM_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, refgr) {
    .Call('_trajeR_IEM_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, refgr)
}

piikIntern_cpp <- function(theta, i, k, ng, X) {
    .Call('_trajeR_piikIntern_cpp', PACKAGE = 'trajeR', theta, i, k, ng, X)
}

muikt_cpp <- function(beta, nbeta, i, period, A, TCOV, delta, nw, k) {
    .Call('_trajeR_muikt_cpp', PACKAGE = 'trajeR', beta, nbeta, i, period, A, TCOV, delta, nw, k)
}

ftheta_cpp <- function(theta, taux, X, n, ng, period) {
    .Call('_trajeR_ftheta_cpp', PACKAGE = 'trajeR', theta, taux, X, n, ng, period)
}

difftheta_cpp <- function(theta, taux, X, n, ng, period) {
    .Call('_trajeR_difftheta_cpp', PACKAGE = 'trajeR', theta, taux, X, n, ng, period)
}

thethaIRLS_cpp <- function(thetaIRLS, n, ng, X, taux, refgr) {
    .Call('_trajeR_thethaIRLS_cpp', PACKAGE = 'trajeR', thetaIRLS, n, ng, X, taux, refgr)
}

findtheta_cpp <- function(theta, taux, X, n, ng, nx, period, EMIRLS, refgr) {
    .Call('_trajeR_findtheta_cpp', PACKAGE = 'trajeR', theta, taux, X, n, ng, nx, period, EMIRLS, refgr)
}

IEMLOGIT_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, TCOV, nw, refgr) {
    .Call('_trajeR_IEMLOGIT_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, TCOV, nw, refgr)
}

gkLOGIT_cpp <- function(beta, i, k, nbeta, A, Y, TCOV, delta, nw) {
    .Call('_trajeR_gkLOGIT_cpp', PACKAGE = 'trajeR', beta, i, k, nbeta, A, Y, TCOV, delta, nw)
}

difLLOGIT_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOV, nw) {
    .Call('_trajeR_difLLOGIT_cpp', PACKAGE = 'trajeR', param, ng, nx, n, nbeta, A, Y, X, TCOV, nw)
}

likelihoodLOGIT_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOV, nw) {
    .Call('_trajeR_likelihoodLOGIT_cpp', PACKAGE = 'trajeR', param, ng, nx, n, nbeta, A, Y, X, TCOV, nw)
}

ftauxLOGIT_cpp <- function(pi, beta, ng, nbeta, n, A, Y, TCOV, delta, nw, nx, X) {
    .Call('_trajeR_ftauxLOGIT_cpp', PACKAGE = 'trajeR', pi, beta, ng, nbeta, n, A, Y, TCOV, delta, nw, nx, X)
}

likelihoodEMLOGIT_cpp <- function(n, ng, nbeta, beta, pi, A, Y, TCOV, delta, nw) {
    .Call('_trajeR_likelihoodEMLOGIT_cpp', PACKAGE = 'trajeR', n, ng, nbeta, beta, pi, A, Y, TCOV, delta, nw)
}

EMLOGIT_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EMLOGIT_cpp', PACKAGE = 'trajeR', param, ng, nx, n, nbeta, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr)
}

EMLOGITIRLS_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EMLOGITIRLS_cpp', PACKAGE = 'trajeR', param, ng, nx, n, nbeta, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr)
}

gkPois_cpp <- function(beta, i, k, nbeta, A, Y, TCOV, delta, nw) {
    .Call('_trajeR_gkPois_cpp', PACKAGE = 'trajeR', beta, i, k, nbeta, A, Y, TCOV, delta, nw)
}

difLbetakPois_cpp <- function(theta, beta, delta, k, ng, nx, nbeta, n, A, Y, X, TCOV, nw) {
    .Call('_trajeR_difLbetakPois_cpp', PACKAGE = 'trajeR', theta, beta, delta, k, ng, nx, nbeta, n, A, Y, X, TCOV, nw)
}

difLPois_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, TCOV, nw) {
    .Call('_trajeR_difLPois_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, TCOV, nw)
}

likelihoodPois_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, TCOV, nw) {
    .Call('_trajeR_likelihoodPois_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, n, A, Y, X, TCOV, nw)
}

gkZIP_cpp <- function(beta, nu, i, k, nbeta, nnu, A, Y, TCOV, delta, nw) {
    .Call('_trajeR_gkZIP_cpp', PACKAGE = 'trajeR', beta, nu, i, k, nbeta, nnu, A, Y, TCOV, delta, nw)
}

difLZIP_cpp <- function(param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw) {
    .Call('_trajeR_difLZIP_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw)
}

likelihoodZIP_cpp <- function(param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw) {
    .Call('_trajeR_likelihoodZIP_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw)
}

likelihoodEMZIP_cpp <- function(n, ng, nbeta, nnu, beta, nu, pi, A, Y, TCOV, delta, nw) {
    .Call('_trajeR_likelihoodEMZIP_cpp', PACKAGE = 'trajeR', n, ng, nbeta, nnu, beta, nu, pi, A, Y, TCOV, delta, nw)
}

ftauxZIP_cpp <- function(pi, beta, nu, ng, nbeta, nnu, n, A, Y, TCOV, delta, nw, nx, X) {
    .Call('_trajeR_ftauxZIP_cpp', PACKAGE = 'trajeR', pi, beta, nu, ng, nbeta, nnu, n, A, Y, TCOV, delta, nw, nx, X)
}

EMZIP_cpp <- function(param, ng, nx, n, nbeta, nnu, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EMZIP_cpp', PACKAGE = 'trajeR', param, ng, nx, n, nbeta, nnu, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr)
}

EMZIPIRLS_cpp <- function(param, ng, nx, n, nbeta, nnu, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr) {
    .Call('_trajeR_EMZIPIRLS_cpp', PACKAGE = 'trajeR', param, ng, nx, n, nbeta, nnu, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr)
}

IEMZIP_cpp <- function(param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw, refgr) {
    .Call('_trajeR_IEMZIP_cpp', PACKAGE = 'trajeR', param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw, refgr)
}

convtolist_cpp <- function(v, nelt) {
    .Call('_trajeR_convtolist_cpp', PACKAGE = 'trajeR', v, nelt)
}

mPsi_cpp <- function(psi, lng) {
    .Call('_trajeR_mPsi_cpp', PACKAGE = 'trajeR', psi, lng)
}

piikMult_cpp <- function(ltheta, mPsi, i, vk, lng, lX, mk) {
    .Call('_trajeR_piikMult_cpp', PACKAGE = 'trajeR', ltheta, mPsi, i, vk, lng, lX, mk)
}

densityChoice_cpp <- function(beta, alphainit, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw, nuinit, nnuinit, model) {
    .Call('_trajeR_densityChoice_cpp', PACKAGE = 'trajeR', beta, alphainit, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw, nuinit, nnuinit, model)
}

likelihoodMult_cpp <- function(vparam, lng, lnx, lnbeta, ln, lA, lY, lX, lymin, lymax, lTCOVinit, lnw, vp, mk, lnnu, model) {
    .Call('_trajeR_likelihoodMult_cpp', PACKAGE = 'trajeR', vparam, lng, lnx, lnbeta, ln, lA, lY, lX, lymin, lymax, lTCOVinit, lnw, vp, mk, lnnu, model)
}

difLalphaMult_cpp <- function(vparam, lng, lnx, lnbeta, ln, lA, lY, lX, lymin, lymax, lTCOVinit, lnw, vp, mk, lnnu, model) {
    .Call('_trajeR_difLalphaMult_cpp', PACKAGE = 'trajeR', vparam, lng, lnx, lnbeta, ln, lA, lY, lX, lymin, lymax, lTCOVinit, lnw, vp, mk, lnnu, model)
}

ftauxPiikMult_cpp <- function(lthetainit, mPsi, lbeta, lsigmainit, lng, lnbeta, ln, lA, lY, lymin, lymax, lTCOVinit, ldelta, lnw, lnx, lX, mk, vp, nuinit, nnuinit, model) {
    .Call('_trajeR_ftauxPiikMult_cpp', PACKAGE = 'trajeR', lthetainit, mPsi, lbeta, lsigmainit, lng, lnbeta, ln, lA, lY, lymin, lymax, lTCOVinit, ldelta, lnw, lnx, lX, mk, vp, nuinit, nnuinit, model)
}

likelihoodMultEM_cpp <- function(lthetainit, mPsi, lbeta, lsigmainit, lng, lnx, lnbeta, ln, lA, lY, lX, lymin, lymax, lTCOVinit, ldelta, lnw, mk, mprob, vp, nuinit, nnuinit, model) {
    .Call('_trajeR_likelihoodMultEM_cpp', PACKAGE = 'trajeR', lthetainit, mPsi, lbeta, lsigmainit, lng, lnx, lnbeta, ln, lA, lY, lX, lymin, lymax, lTCOVinit, ldelta, lnw, mk, mprob, vp, nuinit, nnuinit, model)
}

EMCNORMparam <- function(beta, nw, ng, n, period, j, nbeta, Y, lA, taux, nbetacum, lTCOV, ldelta) {
    .Call('_trajeR_EMCNORMparam', PACKAGE = 'trajeR', beta, nw, ng, n, period, j, nbeta, Y, lA, taux, nbetacum, lTCOV, ldelta)
}

EMLOGITparam <- function(beta, nw, ng, n, period, j, nbeta, Y, lA, taux, nbetacum, lTCOV, ldelta) {
    .Call('_trajeR_EMLOGITparam', PACKAGE = 'trajeR', beta, nw, ng, n, period, j, nbeta, Y, lA, taux, nbetacum, lTCOV, ldelta)
}

EMZIPparam <- function(beta, nu, nw, ng, n, period, j, nbeta, nnu, Y, lA, taux, nbetacum, nnucum, ndeltacum, lTCOVinit, ldeltainit) {
    .Call('_trajeR_EMZIPparam', PACKAGE = 'trajeR', beta, nu, nw, ng, n, period, j, nbeta, nnu, Y, lA, taux, nbetacum, nnucum, ndeltacum, lTCOVinit, ldeltainit)
}

EMMult_cpp <- function(lparam, lng, lnx, lnbeta, lnnu, ln, lA, lY, lX, lymin, lymax, lTCOVinit, lnw, mk, vp, model, itermax, EMIRLS) {
    .Call('_trajeR_EMMult_cpp', PACKAGE = 'trajeR', lparam, lng, lnx, lnbeta, lnnu, ln, lA, lY, lX, lymin, lymax, lTCOVinit, lnw, mk, vp, model, itermax, EMIRLS)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_trajeR_RcppExport_registerCCallable', PACKAGE = 'trajeR')
})
