# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gkCNORM_cpp <- function(beta, sigma, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw) {
    .Call(`_trajeR_gkCNORM_cpp`, beta, sigma, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw)
}

difLalpha_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call(`_trajeR_difLalpha_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

difLalphaunique_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call(`_trajeR_difLalphaunique_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

Likelihoodalpha_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call(`_trajeR_Likelihoodalpha_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

EM_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EM_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

piik_cpp <- function(theta, i, k, ng, X) {
    .Call(`_trajeR_piik_cpp`, theta, i, k, ng, X)
}

ftheta_cpp <- function(theta, taux, X, n, ng, period) {
    .Call(`_trajeR_ftheta_cpp`, theta, taux, X, n, ng, period)
}

difftheta_cpp <- function(theta, taux, X, n, ng, period) {
    .Call(`_trajeR_difftheta_cpp`, theta, taux, X, n, ng, period)
}

thethaIRLS_cpp <- function(thetaIRLS, n, ng, X, taux, refgr) {
    .Call(`_trajeR_thethaIRLS_cpp`, thetaIRLS, n, ng, X, taux, refgr)
}

findtheta_cpp <- function(theta, taux, X, n, ng, nx, period, EMIRLS, refgr) {
    .Call(`_trajeR_findtheta_cpp`, theta, taux, X, n, ng, nx, period, EMIRLS, refgr)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_trajeR_RcppExport_registerCCallable', PACKAGE = 'trajeR')
})
