# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gkCNORM_cpp <- function(beta, sigma, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw) {
    .Call(`_trajeR_gkCNORM_cpp`, beta, sigma, i, k, nbeta, A, Y, ymin, ymax, TCOV, delta, nw)
}

difLalpha_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call(`_trajeR_difLalpha_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

difLalphaunique_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call(`_trajeR_difLalphaunique_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

Likelihoodalpha_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call(`_trajeR_Likelihoodalpha_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

likelihoodCNORM_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw) {
    .Call(`_trajeR_likelihoodCNORM_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw)
}

likelihoodEM_cpp <- function(n, ng, nbeta, beta, sigma, pi, A, Y, ymin, ymax, TCOV, delta, nw) {
    .Call(`_trajeR_likelihoodEM_cpp`, n, ng, nbeta, beta, sigma, pi, A, Y, ymin, ymax, TCOV, delta, nw)
}

ftauxCNORM_cpp <- function(pi, beta, sigma, ng, nbeta, n, A, Y, ymin, ymax, TCOV, delta, nw, nx, X) {
    .Call(`_trajeR_ftauxCNORM_cpp`, pi, beta, sigma, ng, nbeta, n, A, Y, ymin, ymax, TCOV, delta, nw, nx, X)
}

EM_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EM_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

EMSigmaunique_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EMSigmaunique_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

EMCensored_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EMCensored_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

EMCensoredSigmaunique_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EMCensoredSigmaunique_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, itermax, EMIRLS, refgr)
}

IEM_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, refgr) {
    .Call(`_trajeR_IEM_cpp`, param, ng, nx, nbeta, n, A, Y, X, ymin, ymax, TCOV, nw, refgr)
}

#' piik_cpp
#' 
#' Calculate the membership probability to group k for a individual i.
#'
#' @param theta a vector of real with the value of theta parameters.
#' @param i a integer. The index of the data which is used to calculate the probability of group belonging.
#' @param k a integer. The numerous of group.
#' @param ng a integer. The number of groups.
#' @param X a matrix. The covariate that influence the group belonging probability.
#'
#' @return A vector of real. The probability for an individual to belonging at each group.
#' @export
#'
#' piik(theta, i, k, ng, X)
piik_cpp <- function(theta, i, k, ng, X) {
    .Call(`_trajeR_piik_cpp`, theta, i, k, ng, X)
}

muikt_cpp <- function(beta, nbeta, i, period, A, TCOV, delta, nw, k) {
    .Call(`_trajeR_muikt_cpp`, beta, nbeta, i, period, A, TCOV, delta, nw, k)
}

ftheta_cpp <- function(theta, taux, X, n, ng, period) {
    .Call(`_trajeR_ftheta_cpp`, theta, taux, X, n, ng, period)
}

difftheta_cpp <- function(theta, taux, X, n, ng, period) {
    .Call(`_trajeR_difftheta_cpp`, theta, taux, X, n, ng, period)
}

thethaIRLS_cpp <- function(thetaIRLS, n, ng, X, taux, refgr) {
    .Call(`_trajeR_thethaIRLS_cpp`, thetaIRLS, n, ng, X, taux, refgr)
}

findtheta_cpp <- function(theta, taux, X, n, ng, nx, period, EMIRLS, refgr) {
    .Call(`_trajeR_findtheta_cpp`, theta, taux, X, n, ng, nx, period, EMIRLS, refgr)
}

IEMLOGIT_cpp <- function(param, ng, nx, nbeta, n, A, Y, X, TCOV, nw, refgr) {
    .Call(`_trajeR_IEMLOGIT_cpp`, param, ng, nx, nbeta, n, A, Y, X, TCOV, nw, refgr)
}

gkLOGIT_cpp <- function(beta, i, k, nbeta, A, Y, TCOV, delta, nw) {
    .Call(`_trajeR_gkLOGIT_cpp`, beta, i, k, nbeta, A, Y, TCOV, delta, nw)
}

difLthetakLOGIT_cpp <- function(theta, beta, delta, k, ng, nx, n, nbeta, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_difLthetakLOGIT_cpp`, theta, beta, delta, k, ng, nx, n, nbeta, A, Y, X, TCOV, nw)
}

difLbetakLOGIT_cpp <- function(theta, beta, delta, k, ng, nx, n, nbeta, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_difLbetakLOGIT_cpp`, theta, beta, delta, k, ng, nx, n, nbeta, A, Y, X, TCOV, nw)
}

difLdeltakLOGIT_cpp <- function(theta, beta, delta, k, ng, nx, n, nbeta, A, Y, X, initTCOV, nw) {
    .Call(`_trajeR_difLdeltakLOGIT_cpp`, theta, beta, delta, k, ng, nx, n, nbeta, A, Y, X, initTCOV, nw)
}

difLLOGIT_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_difLLOGIT_cpp`, param, ng, nx, n, nbeta, A, Y, X, TCOV, nw)
}

likelihoodLOGIT_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_likelihoodLOGIT_cpp`, param, ng, nx, n, nbeta, A, Y, X, TCOV, nw)
}

ftauxLOGIT_cpp <- function(pi, beta, ng, nbeta, n, A, Y, TCOV, delta, nw, nx, X) {
    .Call(`_trajeR_ftauxLOGIT_cpp`, pi, beta, ng, nbeta, n, A, Y, TCOV, delta, nw, nx, X)
}

QbetakLOGIT_cpp <- function(betak, taux, k, n, ng, nbeta, A, Y, TCOV, deltainit, nw) {
    .Call(`_trajeR_QbetakLOGIT_cpp`, betak, taux, k, n, ng, nbeta, A, Y, TCOV, deltainit, nw)
}

QdeltakLOGIT_cpp <- function(deltak, taux, k, n, ng, nbeta, A, Y, TCOV, beta, nw) {
    .Call(`_trajeR_QdeltakLOGIT_cpp`, deltak, taux, k, n, ng, nbeta, A, Y, TCOV, beta, nw)
}

difQbetakLOGIT_cpp <- function(betak, taux, k, n, ng, nbeta, A, Y, TCOV, deltainit, nw) {
    .Call(`_trajeR_difQbetakLOGIT_cpp`, betak, taux, k, n, ng, nbeta, A, Y, TCOV, deltainit, nw)
}

difQdeltakLOGIT_cpp <- function(deltak, taux, k, n, ng, nbeta, A, Y, TCOV, beta, nw) {
    .Call(`_trajeR_difQdeltakLOGIT_cpp`, deltak, taux, k, n, ng, nbeta, A, Y, TCOV, beta, nw)
}

QbetaLOGIT_cpp <- function(beta, taux, n, ng, nbeta, A, Y, TCOV, delta, nw) {
    .Call(`_trajeR_QbetaLOGIT_cpp`, beta, taux, n, ng, nbeta, A, Y, TCOV, delta, nw)
}

difQbetaLOGIT_cpp <- function(beta, taux, n, ng, nbeta, A, Y, TCOV, delta, nw) {
    .Call(`_trajeR_difQbetaLOGIT_cpp`, beta, taux, n, ng, nbeta, A, Y, TCOV, delta, nw)
}

likelihoodEMLOGIT_cpp <- function(n, ng, nbeta, beta, pi, A, Y, TCOV, delta, nw) {
    .Call(`_trajeR_likelihoodEMLOGIT_cpp`, n, ng, nbeta, beta, pi, A, Y, TCOV, delta, nw)
}

EMLOGIT_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EMLOGIT_cpp`, param, ng, nx, n, nbeta, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr)
}

EMLOGITIRLS_cpp <- function(param, ng, nx, n, nbeta, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EMLOGITIRLS_cpp`, param, ng, nx, n, nbeta, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr)
}

gkZIP_cpp <- function(beta, nu, i, k, nbeta, nnu, A, Y, TCOV, delta, nw) {
    .Call(`_trajeR_gkZIP_cpp`, beta, nu, i, k, nbeta, nnu, A, Y, TCOV, delta, nw)
}

difLthetakZIP_cpp <- function(theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_difLthetakZIP_cpp`, theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw)
}

difLbetakZIP_cpp <- function(theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_difLbetakZIP_cpp`, theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw)
}

difLnukZIP_cpp <- function(theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_difLnukZIP_cpp`, theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw)
}

difLdeltakZIP_cpp <- function(theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOVinit, nw) {
    .Call(`_trajeR_difLdeltakZIP_cpp`, theta, beta, nu, delta, k, ng, nx, nbeta, nnu, n, A, Y, X, TCOVinit, nw)
}

difLZIP_cpp <- function(param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_difLZIP_cpp`, param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw)
}

likelihoodZIP_cpp <- function(param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw) {
    .Call(`_trajeR_likelihoodZIP_cpp`, param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw)
}

likelihoodEMZIP_cpp <- function(n, ng, nbeta, nnu, beta, nu, pi, A, Y, TCOV, delta, nw) {
    .Call(`_trajeR_likelihoodEMZIP_cpp`, n, ng, nbeta, nnu, beta, nu, pi, A, Y, TCOV, delta, nw)
}

ftauxZIP_cpp <- function(pi, beta, nu, ng, nbeta, nnu, n, A, Y, TCOV, delta, nw, nx, X) {
    .Call(`_trajeR_ftauxZIP_cpp`, pi, beta, nu, ng, nbeta, nnu, n, A, Y, TCOV, delta, nw, nx, X)
}

fzkSikt_cpp <- function(pi, beta, nu, zk, k, i, t, ng, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum, period, nbetacum, nnucum) {
    .Call(`_trajeR_fzkSikt_cpp`, pi, beta, nu, zk, k, i, t, ng, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum, period, nbetacum, nnucum)
}

fSikt_cpp <- function(pi, beta, nu, k, i, t, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum, period, nbetacum, nnucum) {
    .Call(`_trajeR_fSikt_cpp`, pi, beta, nu, k, i, t, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum, period, nbetacum, nnucum)
}

QbetakZIP_cpp <- function(beta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum) {
    .Call(`_trajeR_QbetakZIP_cpp`, beta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum)
}

QnukZIP_cpp <- function(nu, zk, Sikt, k, nbeta, nnu, n, A, Y) {
    .Call(`_trajeR_QnukZIP_cpp`, nu, zk, Sikt, k, nbeta, nnu, n, A, Y)
}

QdeltakZIP_cpp <- function(delta, zk, zkSit, k, nbeta, nnu, n, A, Y, TCOV, beta, nw, ndeltacum) {
    .Call(`_trajeR_QdeltakZIP_cpp`, delta, zk, zkSit, k, nbeta, nnu, n, A, Y, TCOV, beta, nw, ndeltacum)
}

QbetadeltakZIP_cpp <- function(betadelta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, nw) {
    .Call(`_trajeR_QbetadeltakZIP_cpp`, betadelta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, nw)
}

difQbetakZIP_cpp <- function(beta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum) {
    .Call(`_trajeR_difQbetakZIP_cpp`, beta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, delta, nw, ndeltacum)
}

difQnukZIP_cpp <- function(nu, zk, Sikt, k, nbeta, nnu, n, A, Y) {
    .Call(`_trajeR_difQnukZIP_cpp`, nu, zk, Sikt, k, nbeta, nnu, n, A, Y)
}

difQdeltakZIP_cpp <- function(delta, zk, zkSit, k, nbeta, nnu, n, A, Y, TCOV, beta, nw, ndeltacum) {
    .Call(`_trajeR_difQdeltakZIP_cpp`, delta, zk, zkSit, k, nbeta, nnu, n, A, Y, TCOV, beta, nw, ndeltacum)
}

difQbetadeltakZIP_cpp <- function(betadelta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, nw) {
    .Call(`_trajeR_difQbetadeltakZIP_cpp`, betadelta, zk, Sikt, k, nbeta, nnu, n, A, Y, TCOV, nw)
}

EMZIP_cpp <- function(param, ng, nx, n, nbeta, nnu, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EMZIP_cpp`, param, ng, nx, n, nbeta, nnu, A, Y, X, TCOV, nw, itermax, EMIRLS, refgr)
}

EMZIPIRLS_cpp <- function(param, ng, nx, n, nbeta, nnu, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr) {
    .Call(`_trajeR_EMZIPIRLS_cpp`, param, ng, nx, n, nbeta, nnu, A, Y, X, TCOVinit, nw, itermax, EMIRLS, refgr)
}

lambdaikt_cpp <- function(k, i, t, nbeta, nbetacum, A, beta, TCOV, period, delta, ndeltacum, nw) {
    .Call(`_trajeR_lambdaikt_cpp`, k, i, t, nbeta, nbetacum, A, beta, TCOV, period, delta, ndeltacum, nw)
}

rhoikt_cpp <- function(k, i, t, nnu, nnucum, A, nu) {
    .Call(`_trajeR_rhoikt_cpp`, k, i, t, nnu, nnucum, A, nu)
}

IEMZIP_cpp <- function(param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw, refgr) {
    .Call(`_trajeR_IEMZIP_cpp`, param, ng, nx, nbeta, nnu, n, A, Y, X, TCOV, nw, refgr)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_trajeR_RcppExport_registerCCallable', PACKAGE = 'trajeR')
})
